In [1]:
!pip install opendatasets

In [2]:
# importing all the necessary libraries
import opendatasets as od
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Dense,Conv2D, MaxPooling2D, Flatten
from tensorflow.keras.models import Sequential

In [3]:
od.download("https://www.kaggle.com/sanikamal/horses-or-humans-dataset")

Skipping, found downloaded files in "./horses-or-humans-dataset" (use force=True to force download)


In [4]:
# Getting horse and human training images path
import os
horse_image = os.listdir('/content/horses-or-humans-dataset/horse-or-human/train/horses')
human_image = os.listdir('/content/horses-or-humans-dataset/horse-or-human/train/humans')
print(f'Length of horse is - ', len(horse_image))
print(f'Length of human is - ', len(human_image))

Length of horse is -  500
Length of human is -  527


Getting Human and Horse Images together

In [5]:
import cv2
images = []
labels = []

# horse images
horse_folder_path = "/content/horses-or-humans-dataset/horse-or-human/train/horses" # horse train path
for image in horse_image:
  img_path = os.path.join(horse_folder_path, image)
  img = cv2.imread(img_path)
  img = cv2.resize(img, (64,64))   # resizing the images
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # converting images from BGR to RGB colour
  images.append(img)
  labels.append(0)

# human images
human_images_folder_path = "/content/horses-or-humans-dataset/horse-or-human/train/humans"  # human train path
for image in human_image:
  img_path = os.path.join(human_images_folder_path, image)
  img = cv2.imread(img_path)
  img = cv2.resize(img, (64,64))   # resizing the images
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # converting images from BGR to RGB colour
  images.append(img)
  labels.append(1)

print(f'Length of images is - ', len(images))
print(f'Length of labels is - ', len(labels))

Length of images is -  1027
Length of labels is -  1027


In [6]:
import numpy as np

images = np.array(images)
labels = np.array(labels)

Splitting the data for training and testing

In [7]:
xtrain,xtest,ytrain,ytest = train_test_split(images,labels,test_size = 0.2, random_state=53)
print(f'xtrain shape is - ', xtrain.shape)
print(f'xtest shape is - ', xtest.shape)

xtrain shape is -  (821, 64, 64, 3)
xtest shape is -  (206, 64, 64, 3)


In [8]:
xtrain

array([[[[121, 165, 231],
         [119, 162, 229],
         [118, 161, 228],
         ...,
         [102, 143, 210],
         [102, 143, 209],
         [102, 143, 210]],

        [[122, 165, 232],
         [120, 163, 229],
         [120, 163, 229],
         ...,
         [102, 143, 210],
         [103, 144, 210],
         [102, 144, 210]],

        [[124, 166, 232],
         [121, 165, 231],
         [120, 163, 229],
         ...,
         [103, 145, 212],
         [103, 145, 212],
         [103, 144, 212]],

        ...,

        [[230, 196, 164],
         [227, 193, 163],
         [227, 193, 163],
         ...,
         [207, 180, 152],
         [209, 181, 153],
         [207, 179, 150]],

        [[236, 200, 171],
         [234, 200, 172],
         [231, 196, 168],
         ...,
         [210, 180, 152],
         [208, 180, 152],
         [212, 183, 153]],

        [[233, 199, 173],
         [229, 195, 167],
         [226, 193, 164],
         ...,
         [209, 182, 153],
        

In [9]:
xtrain = xtrain / 255.0
print(xtrain)
xtest = xtest / 255.0

[[[[0.4745098  0.64705882 0.90588235]
   [0.46666667 0.63529412 0.89803922]
   [0.4627451  0.63137255 0.89411765]
   ...
   [0.4        0.56078431 0.82352941]
   [0.4        0.56078431 0.81960784]
   [0.4        0.56078431 0.82352941]]

  [[0.47843137 0.64705882 0.90980392]
   [0.47058824 0.63921569 0.89803922]
   [0.47058824 0.63921569 0.89803922]
   ...
   [0.4        0.56078431 0.82352941]
   [0.40392157 0.56470588 0.82352941]
   [0.4        0.56470588 0.82352941]]

  [[0.48627451 0.65098039 0.90980392]
   [0.4745098  0.64705882 0.90588235]
   [0.47058824 0.63921569 0.89803922]
   ...
   [0.40392157 0.56862745 0.83137255]
   [0.40392157 0.56862745 0.83137255]
   [0.40392157 0.56470588 0.83137255]]

  ...

  [[0.90196078 0.76862745 0.64313725]
   [0.89019608 0.75686275 0.63921569]
   [0.89019608 0.75686275 0.63921569]
   ...
   [0.81176471 0.70588235 0.59607843]
   [0.81960784 0.70980392 0.6       ]
   [0.81176471 0.70196078 0.58823529]]

  [[0.9254902  0.78431373 0.67058824]
   [0.9

Training the CNN model

In [10]:
model = Sequential() # brain without neurons

#Conv2D KERNELS LAYERS
#MaxPooling2D MAXPOOLING LAYERS
#Flatten MATRIX => 1D ARRAY(1D VECTOR)

model.add(Conv2D(32,(3,3), activation = 'relu', input_shape = (64,64,3))) #INPUT LAYER
model.add(MaxPooling2D(2,2))
# first cnn block

model.add(Conv2D(64,(3,3), activation = 'relu'))
model.add(MaxPooling2D(2,2))
# 2nd cnn block

model.add(Conv2D(64,(3,3), activation = 'relu'))
model.add(MaxPooling2D(2,2))
# 3rd cnn block

model.add(Conv2D(64,(3,3), activation = 'relu'))

model.add(Flatten())

#ann
model.add(Dense(64, activation = "relu")) #fcl
model.add(Dense(1,activation = "sigmoid")) #output layer

model.compile(optimizer = "adam", loss = "binary_crossentropy" , metrics = ["accuracy"])

model.fit(xtrain,ytrain, epochs = 3 , batch_size = 32 ,validation_data = (xtest,ytest))

Epoch 1/3
26/26 [==============================] - 8s 62ms/step - loss: 0.5837 - accuracy: 0.6870 - val_loss: 0.2746 - val_accuracy: 0.9369
Epoch 2/3
26/26 [==============================] - 0s 14ms/step - loss: 0.2201 - accuracy: 0.9172 - val_loss: 0.1945 - val_accuracy: 0.9272
Epoch 3/3
26/26 [==============================] - 0s 12ms/step - loss: 0.1269 - accuracy: 0.9537 - val_loss: 0.1099 - val_accuracy: 0.9466


Checking prediction of model on Horse image

In [11]:
import cv2
import numpy as np

img_path = "/content/horses-or-humans-dataset/horse-or-human/validation/horses/horse1-122.png" # horse val image path
image = cv2.imread(img_path)
image = cv2.resize(image,(64,64))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

In [12]:
image.shape

(64, 64, 3)

In [13]:
image = np.expand_dims(image, axis = 0)  # increasing the image dimension
print(f'image shape - ', image.shape)

image shape -  (1, 64, 64, 3)


In [14]:
image

array([[[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
        

In [15]:
image = image / 255.0  # normalizing the image
print(image)

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]


In [16]:
prediction = model.predict(image)

1/1 [==============================] - 1s 520ms/step


In [17]:
prediction

array([[0.01070702]], dtype=float32)

In [18]:
prediction[0][0]

0.010707018

In [19]:
# setting threshold for prediction
if prediction[0][0] >= 0.5:
  print("1 => Human")
else:
  print("0 => Horse")

0 => Horse


Checking prediction of model on Human image

In [20]:
import cv2
import numpy as np

img_path = "/content/horses-or-humans-dataset/horse-or-human/validation/humans/valhuman01-03.png" # human val image path
image = cv2.imread(img_path)
image = cv2.resize(image,(64,64))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image = np.expand_dims(image, axis = 0)
image = image / 255.0
prediction = model.predict(image)
if prediction[0][0] >= 0.5:
  print("1 => Human")
else:
  print("0 => Horse")

1/1 [==============================] - 0s 117ms/step
1 => Human


Evaluating the models performance

In [21]:
model.evaluate(xtest,ytest)

7/7 [==============================] - 0s 11ms/step - loss: 0.1099 - accuracy: 0.9466


[0.1098906472325325, 0.946601927280426]