In [1]:
!pip install opendatasets

In [2]:
# importing all the necessary libraries
import opendatasets as od
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D, MaxPooling2D, Flatten
import cv2
import numpy as np

In [3]:
od.download("https://www.kaggle.com/datasets/arunrk7/surface-crack-detection")

Skipping, found downloaded files in "./surface-crack-detection" (use force=True to force download)


In [4]:
import os
negativeimages = os.listdir("/content/surface-crack-detection/Negative")  # importing negative images
print(len(negativeimages))

20000


In [5]:
negativeimages = negativeimages[:5000]  #taking only 5000 images out of 20000 for training
print(len(negativeimages))

5000


Data/image preprocessing

In [6]:
images = []
labels = []
for image in negativeimages:   # taking image from neagativeimages folders
  print(image)
  print("===")

Streaming output truncated to the last 5000 lines.
13454.jpg
===
13193.jpg
===
07028.jpg
===
13007.jpg
===
04959.jpg
===
07100.jpg
===
10728.jpg
===
13220.jpg
===
01920.jpg
===
17701.jpg
===
05219.jpg
===
10576.jpg
===
04942.jpg
===
10683.jpg
===
08092.jpg
===
16486.jpg
===
18068.jpg
===
11821.jpg
===
11868.jpg
===
19740.jpg
===
03857.jpg
===
11802.jpg
===
13980.jpg
===
11928.jpg
===
13267.jpg
===
12192.jpg
===
15089.jpg
===
10091.jpg
===
07995.jpg
===
07800.jpg
===
09939.jpg
===
04158.jpg
===
12123.jpg
===
05900.jpg
===
04892.jpg
===
14469.jpg
===
18257.jpg
===
08416.jpg
===
08003.jpg
===
13768.jpg
===
10650.jpg
===
07303.jpg
===
14139.jpg
===
09275.jpg
===
15035.jpg
===
00807.jpg
===
15108.jpg
===
05826.jpg
===
14100.jpg
===
07375.jpg
===
18145.jpg
===
17277.jpg
===
19649.jpg
===
06226.jpg
===
18879.jpg
===
09988.jpg
===
14978.jpg
===
00551.jpg
===
17825.jpg
===
14389.jpg
===
06282.jpg
===
12199.jpg
===
11819.jpg
===
07920.jpg
===
11830.jpg
===
01576.jpg
===
11981.jpg
===
14924.jpg
=

In [7]:
images = []
labels = []
negative_images_folder_path = "/content/surface-crack-detection/Negative/"
for image in negativeimages:
  img_path = os.path.join(negative_images_folder_path, image) # joining the path to the images in neagativeimages folder
  print(img_path)
  print("===")

Streaming output truncated to the last 5000 lines.
/content/surface-crack-detection/Negative/13454.jpg
===
/content/surface-crack-detection/Negative/13193.jpg
===
/content/surface-crack-detection/Negative/07028.jpg
===
/content/surface-crack-detection/Negative/13007.jpg
===
/content/surface-crack-detection/Negative/04959.jpg
===
/content/surface-crack-detection/Negative/07100.jpg
===
/content/surface-crack-detection/Negative/10728.jpg
===
/content/surface-crack-detection/Negative/13220.jpg
===
/content/surface-crack-detection/Negative/01920.jpg
===
/content/surface-crack-detection/Negative/17701.jpg
===
/content/surface-crack-detection/Negative/05219.jpg
===
/content/surface-crack-detection/Negative/10576.jpg
===
/content/surface-crack-detection/Negative/04942.jpg
===
/content/surface-crack-detection/Negative/10683.jpg
===
/content/surface-crack-detection/Negative/08092.jpg
===
/content/surface-crack-detection/Negative/16486.jpg
===
/content/surface-crack-detection/Negative/18068.jpg
=

In [8]:
import cv2
images = []
labels = []
negative_images_folder_path = "/content/surface-crack-detection/Negative/"
for image in negativeimages:
  img_path = os.path.join(negative_images_folder_path, image)
  img = cv2.imread(img_path)
  img = cv2.resize(img, (64,64))   # resizing the images
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # converting images from BGR to RGB colour
  images.append(img)
  labels.append(0)   # 0 label for negative images

In [9]:
# repeating the process for positive images
import os
positiveimages = os.listdir("/content/surface-crack-detection/Positive/")
positiveimages = positiveimages[:5000]
positive_images_folder_path = "/content/surface-crack-detection/Positive/"
for image in positiveimages:
  img_path = os.path.join(positive_images_folder_path, image)
  img = cv2.imread(img_path)
  img = cv2.resize(img, (64,64))
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  images.append(img)
  labels.append(1)

In [10]:
len(images)

10000

In [11]:
len(labels)

10000

In [12]:
import numpy as np

images = np.array(images)
labels = np.array(labels)

Splitting data for training and testing

In [13]:
xtrain,xtest,ytrain,ytest = train_test_split(images,labels,test_size = 0.2, random_state=53)
print(f'xtrain shape - ', xtrain.shape)
print(f'xtest shape - ', xtest.shape)

xtrain shape -  (8000, 64, 64, 3)
xtest shape -  (2000, 64, 64, 3)


In [14]:
xtrain

array([[[[175, 172, 167],
         [183, 180, 175],
         [182, 180, 174],
         ...,
         [158, 154, 150],
         [164, 161, 156],
         [169, 166, 161]],

        [[173, 170, 165],
         [184, 181, 176],
         [188, 185, 180],
         ...,
         [164, 161, 156],
         [165, 162, 157],
         [167, 164, 159]],

        [[177, 174, 169],
         [171, 169, 163],
         [173, 170, 165],
         ...,
         [164, 161, 156],
         [169, 166, 161],
         [170, 167, 162]],

        ...,

        [[192, 189, 184],
         [196, 193, 188],
         [195, 192, 187],
         ...,
         [153, 150, 145],
         [179, 175, 171],
         [168, 164, 160]],

        [[191, 188, 184],
         [194, 191, 186],
         [192, 189, 184],
         ...,
         [169, 166, 161],
         [180, 177, 172],
         [175, 172, 167]],

        [[189, 186, 181],
         [189, 187, 182],
         [190, 183, 180],
         ...,
         [173, 170, 165],
        

In [15]:
xtrain = xtrain / 255.0
print(xtrain)
xtest = xtest / 255.0

[[[[0.68627451 0.6745098  0.65490196]
   [0.71764706 0.70588235 0.68627451]
   [0.71372549 0.70588235 0.68235294]
   ...
   [0.61960784 0.60392157 0.58823529]
   [0.64313725 0.63137255 0.61176471]
   [0.6627451  0.65098039 0.63137255]]

  [[0.67843137 0.66666667 0.64705882]
   [0.72156863 0.70980392 0.69019608]
   [0.7372549  0.7254902  0.70588235]
   ...
   [0.64313725 0.63137255 0.61176471]
   [0.64705882 0.63529412 0.61568627]
   [0.65490196 0.64313725 0.62352941]]

  [[0.69411765 0.68235294 0.6627451 ]
   [0.67058824 0.6627451  0.63921569]
   [0.67843137 0.66666667 0.64705882]
   ...
   [0.64313725 0.63137255 0.61176471]
   [0.6627451  0.65098039 0.63137255]
   [0.66666667 0.65490196 0.63529412]]

  ...

  [[0.75294118 0.74117647 0.72156863]
   [0.76862745 0.75686275 0.7372549 ]
   [0.76470588 0.75294118 0.73333333]
   ...
   [0.6        0.58823529 0.56862745]
   [0.70196078 0.68627451 0.67058824]
   [0.65882353 0.64313725 0.62745098]]

  [[0.74901961 0.7372549  0.72156863]
   [0.7

Creating and training the CNN model

In [16]:
model = Sequential() # brain without neurons
#Conv2D KERNELS LAYERS
#MaxPooling2D MAXPOOLING LAYERS
#Flatten MATRIX => 1D ARRAY(1D VECTOR)

model.add(Conv2D(32,(3,3), activation = 'relu', input_shape = (64,64,3))) #INPUT LAYER
model.add(MaxPooling2D(2,2))
# first cnn block

model.add(Conv2D(64,(3,3), activation = 'relu'))
model.add(MaxPooling2D(2,2))
# 2nd cnn block

model.add(Conv2D(64,(3,3), activation = 'relu'))
model.add(MaxPooling2D(2,2))
# 3rd cnn block

model.add(Conv2D(64,(3,3), activation = 'relu'))

model.add(Flatten())
#ann
model.add(Dense(64, activation = "relu")) #fcl
model.add(Dense(1,activation = "sigmoid")) #output layer

model.compile(optimizer = "adam", loss = "binary_crossentropy" , metrics = ["accuracy"])

model.fit(xtrain,ytrain, epochs = 3 , batch_size = 32 ,validation_data = (xtest,ytest))

Epoch 1/3
250/250 [==============================] - 6s 9ms/step - loss: 0.1493 - accuracy: 0.9436 - val_loss: 0.0699 - val_accuracy: 0.9825
Epoch 2/3
250/250 [==============================] - 2s 7ms/step - loss: 0.0511 - accuracy: 0.9852 - val_loss: 0.0729 - val_accuracy: 0.9835
Epoch 3/3
250/250 [==============================] - 2s 6ms/step - loss: 0.0450 - accuracy: 0.9859 - val_loss: 0.0495 - val_accuracy: 0.9850


Checking models predicition on unknown image

In [17]:
img_path = "/content/surface-crack-detection/Negative/00003.jpg"
image = cv2.imread(img_path)
image = cv2.resize(image,(64,64))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

In [18]:
image.shape

(64, 64, 3)

In [19]:
image = np.expand_dims(image, axis = 0)  #expanding the dimension of image
print(f'images shape -', image.shape)

images shape - (1, 64, 64, 3)


In [20]:
image = image / 255.0
print(image)

[[[[0.61568627 0.60392157 0.58431373]
   [0.62745098 0.61960784 0.59607843]
   [0.72941176 0.71764706 0.69803922]
   ...
   [0.75294118 0.74117647 0.72156863]
   [0.75294118 0.74117647 0.72156863]
   [0.74117647 0.7254902  0.71372549]]

  [[0.62352941 0.61176471 0.59215686]
   [0.64705882 0.63529412 0.61568627]
   [0.70980392 0.69803922 0.67843137]
   ...
   [0.76470588 0.75686275 0.73333333]
   [0.75294118 0.74117647 0.72156863]
   [0.75294118 0.7372549  0.7254902 ]]

  [[0.55294118 0.54117647 0.52156863]
   [0.65882353 0.64705882 0.62745098]
   [0.68235294 0.67058824 0.65098039]
   ...
   [0.71764706 0.70588235 0.68627451]
   [0.67843137 0.66666667 0.64705882]
   [0.7372549  0.72156863 0.70980392]]

  ...

  [[0.74117647 0.72156863 0.70588235]
   [0.74901961 0.72941176 0.71372549]
   [0.67058824 0.65098039 0.63529412]
   ...
   [0.66666667 0.65490196 0.63529412]
   [0.67058824 0.6627451  0.64313725]
   [0.81568627 0.80392157 0.78431373]]

  [[0.83529412 0.81568627 0.8       ]
   [0.8

In [21]:
prediction = model.predict(image)
print(prediction)
prediction = prediction[0][0]  # getting value of predicition inside the brackets
print(prediction)

1/1 [==============================] - 0s 304ms/step
[[0.00182186]]
0.0018218637


In [22]:
if prediction >= 0.5:
  print("1 => positive => crack detected")
else:
  print("0 => negative => crack not detected")

0 => negative => crack not detected


Checking prediction on positive cracked image

In [23]:
import cv2
import numpy as np

img_path = "/content/surface-crack-detection/Positive/00003.jpg"
image = cv2.imread(img_path)
image = cv2.resize(image,(64,64))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image = np.expand_dims(image, axis = 0)
image = image / 255.0
prediction = model.predict(image)
if prediction[0][0] >= 0.5:
  print("1 => positive => crack detected")
else:
  print("0 => negative => crack not detected")

1/1 [==============================] - 0s 17ms/step
1 => positive => crack detected


Evaluating models performance

In [24]:
model.evaluate(xtest,ytest)

63/63 [==============================] - 0s 4ms/step - loss: 0.0495 - accuracy: 0.9850


[0.04951568692922592, 0.9850000143051147]